### ISSUE TITLE
Deploy job failed because variable `WebAppNameDev` has double quotes

### ISSUE THREAD

**Issue by pltchuong** [MicrosoftDocs/mslearn-tailspin-spacegame-web-automate#11]
I followed exact steps here... but ended up with job failed, here is the exception:
```
Starting: Azure App Service Deploy: website
==============================================================================
Task         : Azure Web App
Description  : Deploy an Azure Web App for Linux or Windows
Version      : 1.168.3
Author       : Microsoft Corporation
Help         : https://aka.ms/azurewebapptroubleshooting
==============================================================================
Got service connection details for Azure App Service:'"tailspin-space-game-web-dev-8475"'
##[error]Error: Resource '"tailspin-space-game-web-dev-8475"' doesn't exist. Resource should exist before deployment.
Finishing: Azure App Service Deploy: website
```

It was pretty weird because I checked, resources exists as it should and everything else was just fine (including provisioning step). Took me a while to realized `terraform output appservice_name_dev` produces double quotes and the value or variable  `WebAppNameDev` is actually `"tailspin-space-game-web-dev-8475"` (with quotes)

The easiest fix is using  `xargs` when retrieving value from `terraform output`

**Comment by virendrajain** [comment]
Below line will fix above issue
` WebAppNameDev=$(eval echo $(terraform output appservice_name_dev))`

**Comment by pltchuong** [comment]
I ended up with this `WebAppNameDev=$(terraform output appservice_name_dev | xargs)`
